version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one data row per products_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: join key
          - name: products_id
            description: join key
          - name: revenue
            description: total value of products purchased
          - name: quantity
            description: number of products purchased
      - name: product
        identifier: raw_gz_product
        description: greenweez list of products
        columns:
          - name: products_id
            description: primary key for this table
            tests:
              - unique
              - not_null
          - name: purchase price
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key for this table
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: logcost
          - name: ship_cost
