version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one data row per products_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: join key
          - name: products_id
            description: join key
          - name: revenue
            description: total value of products purchased
          - name: quantity
            description: number of products purchased
      - name: product
        identifier: raw_gz_product
        description: greenweez list of products
        columns:
          - name: products_id
            description: primary key for this table
            tests:
              - unique
              - not_null
          - name: purchase price
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key for this table
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: logcost
          - name: ship_cost

models:
  - name: stg_raw_product
  - name: stg_raw_sales
  - name: stg_raw_ship
  - name: int_sales_margin
    description: margin calcultation per order line / product sale
    columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
  - name: int_orders_margin
    description: margin calcultation per order
    columns:
      - name: orders_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order
      - name: quantity
        description: sum of quantity per order
  - name: int_orders_operational
    description: operational margin calcultation per order
    columns:
      - name: operational_margin
        description: Operational margin = margin + shipping fee - log_cost - ship_cost
  - name: finance_days
    description: finance calculation per days
